console.log('Hello World');
console.log(123);
console.log(true);
var greeting = 'Hello';
console.log(greeting);
console.log([1,2,3]);
console.log({a:1, b:2});
console.table({a:1, b:2});

console.error('errror');
console.clear();
console.warn(' warning');
console.time('Hello');
  console.log('HI');
  console.log('HI');
  console.log('HI');
  console.log('HI');
  console.log('HI');
  console.log('HI');
console.timeEnd('Hello');